version: '3.3'

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 9000
    volumes:
      - ./src/:/usr/src/app/
    env_file:
      - .env
    ports:
      - 8008:9000
    restart: always

  mongo:
    image: mongo
    container_name: mongo_local
    restart: always
    volumes:
       - ./mongodb:/data/db
       - ./backups:/backups
    ports:
        - 27017:27017
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root